config/routes.rb
MapsDemo::Application.routes.draw do
  resources :incidents, only: :index do
    collection do
      get 'latest'
    end
  end

   root :to => 'incidents#index'

end

app/models/incident.rb
class Incident < ActiveRecord::Base
  class << self
    def synchronize
      result = RestClient.get("http://traffic.houstontranstar.org/data/layers/incidents_json.js")
      incidents = JSON.parse(result.body)["incidents"]
      incidents.each do |i|
        incident = Incident.new
        incident.location = i["location"]
        incident.description = i["desc"]
        incident.vehicles = i["veh"]
        incident.lanes = i["lanes"]
        incident.status = i["status"]
        incident.reported_at = Chronic.parse i["time"]
        incident.latitude = i["lat"]
        incident.longitude = i["lng"]
        incident.save! rescue nil
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  # GET /incidents
  # GET /incidents.json
  respond_to :json, :html
  def index
    @incidents = Incident.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incidents }
    end
  end

  def latest
    unless @incidents = Rails.cache.fetch("incidents")
      Incident.synchronize
      @incidents = Incident.where(created_at: (Time.now - 3.hours)..Time.now)
      Rails.cache.write('incidents', @incidents.as_json, :expires_in => 5.minutes, :race_condition_ttl => 30.seconds)
    end
     respond_with @incidents
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
    @incident = Incident.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @incident }
    end
  end

  # GET /incidents/new
  # GET /incidents/new.json
  def new
    @incident = Incident.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @incident }
    end
  end

  # GET /incidents/1/edit
  def edit
    @incident = Incident.find(params[:id])
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(params[:incident])

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render json: @incident, status: :created, location: @incident }
      else
        format.html { render action: "new" }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incidents/1
  # PUT /incidents/1.json
  def update
    @incident = Incident.find(params[:id])

    respond_to do |format|
      if @incident.update_attributes(params[:incident])
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident = Incident.find(params[:id])
    @incident.destroy

    respond_to do |format|
      format.html { redirect_to incidents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.haml
= form_for @incident do |f|
  -if @incident.errors.any?
    #error_explanation
      %h2= "#{pluralize(@incident.errors.count, "error")} prohibited this incident from being saved:"
      %ul
        - @incident.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :vehicles
    = f.number_field :vehicles
  .field
    = f.label :lanes
    = f.text_field :lanes
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :time
    = f.datetime_select :time
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions
    = f.submit 'Save'

app/views/incidents/edit.html.haml
%h1 Editing incident

= render 'form'

= link_to 'Show', @incident
\|
= link_to 'Back', incidents_path

app/views/incidents/index.html.haml
#map_canvas{style: "width:600px; height:600px"}

app/views/incidents/new.html.haml
%h1 New incident

= render 'form'

= link_to 'Back', incidents_path

app/views/incidents/show.html.haml
%p#notice= notice

%p
  %b Location:
  = @incident.location
%p
  %b Description:
  = @incident.description
%p
  %b Vehicles:
  = @incident.vehicles
%p
  %b Lanes:
  = @incident.lanes
%p
  %b Status:
  = @incident.status
%p
  %b Time:
  = @incident.time
%p
  %b Latitude:
  = @incident.latitude
%p
  %b Longitude:
  = @incident.longitude

= link_to 'Edit', edit_incident_path(@incident)
\|
= link_to 'Back', incidents_path

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "MapsDemo"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
    = javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_API_KEY"]}&sensor=false"
    :erb
      <script id="sidebar_item" type="text/javascript">
        <h4>{{=description}}</h4>
        <p>{{=location}}<br />
        {{=date}}</p>

      </script>

    :javascript
      var map;
      function initialize() {
        var myOptions = {
          center: new google.maps.LatLng(29.7630556, -95.3630556),
          zoom: 10,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById("map_canvas"),
            myOptions);
        var trafficLayer = new google.maps.TrafficLayer();
        trafficLayer.setMap(map);
      }
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{ENV['GOOGLE_ANALYTICS_CODE']}']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  %body{onload: "initialize()"}
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"}MapsDemo
          .container-fluid.nav-collapse
            %ul.nav
              %li= link_to "Incidents", "/"


    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            Recent Incidents
            %ul.nav.nav-list{id: "incident_list"}

        .span9
          = yield

      %footer
        %p &copy; Solusean 2012
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    :javascript
      $(document).ready(function(){ initialize()})

    = yield :more_js